### ISSUE TITLE
[Solved] Not capture at Win x64, works normal till today.

### ISSUE THREAD

**Issue by Shooshka** [enzy/Scup#15]
It's strange, but from 1 moment Scup stops working, nothing happend when I press PrtSc. Just update to v2 - nothing happens too.
How can I see some debug.log to send it to you?

PS. Using .exe version.
PPS. Thx for fixing #6 #7 ;)

upd: .jar version - same issue.
upd2: After rebooting Windows - all ok, works again. Think it was Java's bug or bug after hibernate mode :(

**Comment by enzy** [comment]
Debug info is available when you run .jar version from command line.

Its strange issue, I will try to replicate it.

**Comment by Shooshka** [comment]
Ok, will remember this. So I think it's really depends on "sleep" and "hibernate" mode, because AFAIR Scup stops working today after resuming from hibernate.. will test now too.

upd: No luck.. test sleep and hibernate with console version - all good. Ok, then will use Scup from console till bug repeats.
PS. From main page - "Local solution: netsh advfirewall set global StatefulFTP disable" - only need if use console version, all works fine without this command if using .exe

upd2: Every time I see in log: Image: 1600x900
But I think I must see resolution of cropped image, no? :)

**Comment by enzy** [comment]
ad upd2: Its little tricky, the original image is from clipboard which is cropped after console print. 
Logic behind that: If image in clipboard is fullscreen then image is going to crop. If its smaller (like Alt+Printscreen) then don't crop it and use it as is (that's what "Monitor all" option is in settings).

**Comment by enzy** [comment]
ad local solution to FTP connection problems: in .exe wrapper is used `-Djava.net.preferIPv4Stack=true` as JVM option by default.

**Comment by Shooshka** [comment]
enzy, thanks for comments, now understand all "tricks", but I think some "Help" section must be in Scup :)

**Comment by enzy** [comment]
Created #16 for help section.
