### ISSUE TITLE
Bug with text selection with ctrl+c and getting screen uploading...

### ISSUE THREAD

**Issue by Shooshka** [enzy/Scup#17]
How to repeat:

1) Open outlook 2010
2) Open any message
3) Double click on 1 word to select it, ctrl+c (or right click - copy)
4) Oooops:
Clearing clipboard...
Processing image...
Image: 623x18
Saving image: 5c86a7a7a3.png
Uploading image to FTP server...
Upload done
http://ishoo.ru/pic/5c86a7a7a3.png

Black stripe as you can see on screen.

Maybe use defineable hotkey to get screenshot/cropped screenshot?)

**Comment by enzy** [comment]
That's the case when you should turn "Monitor all" options off. MS Office have strange clipboard handling, Outlook seems have the same.

ad hotkey: Yea, I tried that in very alpha implementation and it is paint in the ass with Java - so I switched to clipboard monitoring, which (on windows) wokrs great (except MS Office :D)

**Comment by Shooshka** [comment]
Ok, thx for reply and explanations, already uncheck "Monitor all" :) Waiting for new versions with new features :)
PS. Hate Microsoft ><

**Comment by enzy** [comment]
ad new features: I'm experimenting with Dropbox uploading, stay tuned ;)

**Comment by Shooshka** [comment]
Don't using dropbox, using Yandex.Disk (mostly Russian service). Most interst to me from issues - uploading any files and uploading many files in 1 zip archive ;)

**Comment by enzy** [comment]
btw: file uploading implemented in version 3 ;)
