### ISSUE TITLE
OS X 10.8, does not seem to be working..?

### ISSUE THREAD

**Issue by tmikaeld** [enzy/Scup#18]
I tried CMD+shift+4 and CMD+shift+3 but nothing happens. 
Tried copying an image to clipboard, still no go.

**Comment by enzy** [comment]
Thank you for your feedback.
Actually I haven't got a chance to test it on MacOS yet. Scup internals
depends on Java workflow with clipboard.

Dne 6.9.2012 22:22 "tmikaeld" notifications@github.com napsal(a):

**Comment by enzy** [comment]
Well, I managed to run a VirtualBox with MacOS to test it...
Current implementation works, but with strange behavior: Clipboard is monitored only when Scup has active focus, it looks that it's standart java behavior on mac (more at #21).
Aditionally current version saves empty images #22.

So thats for Java platform independence... :/

**Comment by enzy** [comment]
not supported OS for now
